image: node:10

stages:
  - test
  - build
  - zip-and-deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

before_script:
  - npm install
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - 'chmod a+x deploy/deploy.sh'

test:
  stage: test
  script:
    - npm install
    - npm test

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist
    expire_in: 1 day

deploy:
  stage: zip-and-deploy
  script:
    - ./deploy/deploy.sh
